apiVersion: v1
kind: Namespace
metadata:
  name: github-runner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner-sa
  namespace: github-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: github-runner-sa
    namespace: github-runner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner-sa
      containers:
        - name: runner
          image: myoung34/github-runner:latest
          env:
            - name: REPO_URL
              value: "https://github.com/Ashikuroff/backstage-deployment"
            - name: RUNNER_NAME
              value: "kind-cluster-runner"
            - name: RUNNER_LABELS
              value: "kind-runner,self-hosted"
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: runner-token
                  key: token
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          securityContext:
            privileged: true
          volumeMounts:
            - name: runner-data
              mountPath: /runner
        - name: dind
          image: docker:dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            - name: docker-storage
              mountPath: /var/lib/docker
      volumes:
        - name: runner-data
          emptyDir: {}
        - name: docker-storage
          emptyDir: {}
